# ===============================================
# ?? ??
# ===============================================
server:
  port: 8080

spring:
  # ???? ??? ???? local? ?????.
  profiles:
    active: local
  jpa:
    hibernate:
      # ?????? ?? ? ??? ???? ???? ???? ?? ??/?????.
      ddl-auto: update
    properties:
      hibernate:
        # JPA? ???? SQL ??? ???? ??? ?????.
        format_sql: true
        # N+1 ?? ??? ?? ?????.
        default_batch_fetch_size: 100
    # OSIV(Open Session In View)? ?? ??? ??? ? ? ?? ??? ?? ?????.
    open-in-view: false

# SpringDoc OpenAPI (Swagger) ??
springdoc:
  default-produces-media-type: application/json
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html # Swagger UI? ??? ?????.
    operations-sorter: alpha # API ??? ??? ??? ?????.
    tags-sorter: alpha

logging:
  level:
    # SQL ??? DEBUG ??? ??? ???.
    org.hibernate.SQL: debug

---
# ===============================================
# local ?? ?? (?? H2 DB ??)
# ===============================================
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL # H2? MySQL ??? ??
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      # H2 ??????? ??? ?? ? ? ?? ??? ??????.
      enabled: true
      path: /h2-console

---
# ===============================================
# dev ?? ?? (Docker DB ??)
# ===============================================
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    # docker-compose.yml? ??? ??? ??(db)? ???? ?????.
    url: jdbc:mysql://db:3306/boilerplate_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    # docker-compose.yml?? ??? ?? ????? ????? ??????.
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver